### ISSUE TITLE
Shopkeepers compability

### ISSUE THREAD

**Issue by hero23550** [K0bus/CreativeManager2#1]
Enabling the container protection feature also doesn't allow me to change items in my admin shopkeeper made using https://www.spigotmc.org/resources/shopkeepers.80756/ btw it requires creative edit admin shopkeepers. I was hoping if you could detect this plugin in servers and stop the conflicts

**Comment by K0bus** [comment]
Hi,
Do you use CreativeManager or CreativeManager2 ?

**Comment by hero23550** [comment]
> Hi, Do you use CreativeManager or CreativeManager2 ?

this https://www.spigotmc.org/resources/%E2%9A%A1-creativemanager-%E2%9A%A1-customizable-complete-control.75097/
